// Generated by CoffeeScript 1.6.3
(function() {
  window.app = angular.module('app', ['ngRoute', 'ui.bootstrap.modal']);

  window.MainCtrl = [
    '$scope', '$http', '$modal', '$filter', function(self, $http, $modal, $filter) {
      var stored;
      self.awailable_pages = [5, 10, 15, 20, 30, 50, 70, 100];
      self.loading = true;
      self.table = new Table;
      stored = localStorage['mytestconfig'];
      if (typeof Storage !== 'undefined') {
        if (stored) {
          self.table.config = _.assign(self.table.config, $.parseJSON(stored));
        }
      } else {
        console.log('storage can not be used');
      }
      self.$watch('table.config', function(config) {
        localStorage['mytestconfig'] = JSON.stringify(config);
        return self.table.fetch();
      }, true);
      self.table.fetch();
      self.show_details = function(item) {
        return $modal.open({
          templateUrl: 'templates/item_details.html',
          controller: 'DetailsCtrl',
          resolve: {
            item: function() {
              return item;
            }
          }
        });
      };
      return self.get_rclass = function() {
        if (self.table.config.order_reverse) {
          return 'glyphicon-arrow-up';
        }
        return 'glyphicon-arrow-down';
      };
    }
  ];

}).call(this);
