// Generated by CoffeeScript 1.6.3
(function() {
  app.factory('Table', [
    function() {
      var Table;
      return Table = (function() {
        function Table(config) {}

        Table.prototype.fetch = function() {};

        Table.prototype.set_page = function(page) {};

        Table.prototype.toggle_order = function(order) {};

        return Table;

      })();
    }
  ]);

}).call(this);
