// Generated by CoffeeScript 1.6.3
(function() {
  window.app = angular.module('app', []);

  window.MainCtrl = [
    '$scope', '$filter', 'Table', function(self, $filter, Table) {
      self.items_per_page = [5, 10, 15, 20, 30, 50, 70, 100];
      self.loading = true;
      self.table = new Table({
        fetch_path: 'data.json'
      });
      return self.table.fetch();
    }
  ];

}).call(this);
