// Generated by CoffeeScript 1.6.3
(function() {
  window.app = angular.module('app', ['ngRoute', 'ui.bootstrap.modal']);

  window.DetailsCtrl = [
    '$scope', '$modalInstance', 'item', function(self, $modalInstance, item) {
      self.item = _.clone(item);
      return self.ok = function() {
        return $modalInstance.dismiss('cancel');
      };
    }
  ];

}).call(this);
