// Generated by CoffeeScript 1.6.3
(function() {
  app.factory('Table', [
    '$http', '$rootScope', '$filter', function($http, $rootScope, $filter) {
      var Table;
      return Table = (function() {
        Table.prototype.current_page = 0;

        Table.prototype.items = {
          raw: [],
          pages: []
        };

        Table.prototype.config = {
          search: '',
          items_per_page: 5,
          fetch_method: 'get',
          order_by: '',
          order_reverse: false
        };

        function Table(config) {
          var _this = this;
          this.config = _.defaults(config, this.config);
          $rootScope.$watch(function() {
            return _this.config;
          }, function() {
            return _this.foo();
          }, true);
        }

        Table.prototype.fetch = function() {
          var _this = this;
          return $http({
            url: this.config.fetch_path,
            method: this.config.fetch_method
          }).success(function(data) {
            _this.items.raw = angular.fromJson(data);
            return _this.foo();
          });
        };

        Table.prototype.foo = function() {
          var data;
          data = _.clone(this.items.raw);
          data = $filter('filter')(data, this.config.search);
          data = $filter('orderBy')(data, this.config.order_by, this.config.order_reverse);
          if (data.length > this.config.items_per_page) {
            return this.items.pages = ((function() {
              var _results;
              _results = [];
              while (data.length) {
                _results.push(data.splice(0, this.config.items_per_page));
              }
              return _results;
            }).call(this));
          } else {
            return this.items.pages = [data];
          }
        };

        Table.prototype.set_page = function(page) {
          return this.current_page = page;
        };

        Table.prototype.toggle_order = function(order) {
          if (this.config.order_by === order) {
            return this.config.order_reverse = !this.config.order_reverse;
          } else {
            return this.config.order_by = order;
          }
        };

        return Table;

      })();
    }
  ]);

}).call(this);
